import { PersistGate } from 'redux-persist/lib/integration/react';
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'mdr',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <PersistGate loading={null} persistor={persistor}>
      <body className={inter.className}>{children}</body>
      </PersistGate>
    </html>
  )
}
